### ISSUE TITLE
Error knitting vancouver-tree-height-geo.Rmd: Missing 'janitor' package after running renv::activate() on local machine

### ISSUE THREAD

**Issue by ZhengHe-007** [gunishakaur/Dynamic33#10]
Hi all, 

When I tried to knit the final version of our Rmd file on the local repo, it kept showing the error message after I ran renv::activate() on my console. However, Derek who's been working on this file with renv can knit it but all of us who pull the repo from Git Hub can not knit it on our local machine.

Best,

Zheng He

**Comment by ZhengHe-007** [comment]
Here is the comment I received from Professor Daniel: 

Your teammate needs to update the renv.lock file. probably they need to run renv::snapshot() and check in the changes to the file. and then you pull the repo.

you can check the library status with renv::status() and see what packages are missing from the lockfile
[https://rstudio.github.io/renv/articles/renv.html#collaboration]

**Comment by jessiezhang24** [comment]
Thank you for sharing! Same issue here. After running `renv::status()`, I found that there is a mismatch between the installed version of data.table in my environment and the version specified in the renv.lock file (screenshot below).
![image](https://github.com/user-attachments/assets/13fa4707-e351-403b-b03e-78c12ac1c181)

So we may have two options:
	1.	Update the renv.lock file to match the currently installed version using `renv::snapshot()` and commit the changes
	2.	Restore the environment to match the renv.lock file by running `renv::restore()` locally

Any other suggestions or approaches would be greatly appreciated!

Best
Jessie

**Comment by derekrodgers** [comment]
This was resolved

**Comment by derekrodgers** [comment]
This was resolved
