### ISSUE TITLE
Recovering from Accidental Commits

### ISSUE THREAD

**Issue by gunishakaur** [gunishakaur/Dynamic33#11]
Hi everyone,

Accidentally committing changes to the wrong branch is a common issue that can cause confusion and even lead to potential merge conflicts during the development process. For instance, I committed changes to the README file on the Introduction_summary branch, which was not the intended branch for these changes.

This kind of mistake often occurs when working with multiple branches and forgetting to switch to the correct one before making or committing changes. Addressing this error early is crucial to maintain a clean project history and avoid complications during merges or pull requests.

I would like to ask for guidance on how to resolve this issue effectively. How can I move the committed changes to the correct branch while restoring the unintended branch to its original state? Any advice would be greatly appreciated!

Thanks!
Best regards,
Gunisha Kaur

**Comment by gunishakaur** [comment]
Hi everyone,

So after looking at the issue, I see that this issue is very common when working with multiple branches, and thankfully, there is a straightforward solution to resolve it. The goal is to move the committed changes to the correct branch and restore the unintended branch to its original state. Here’s how you can do it:

1. Switch to the Correct Branch:
Start by moving to the branch where the changes should have been committed. For example, if the intended branch is main, use the command:
-git switch main

2. Cherry-Pick the Commit(s):
Copy the changes from the wrong branch to the correct branch using git cherry-pick. Replace <commit-hash> with the hash of the commit you want to move.
-git cherry-pick <commit-hash>
If you need to move a range of commits, you can specify the start and end commit hashes:

-git cherry-pick <start-commit-hash>..<end-commit-hash>

3. Restore the Wrong Branch:
Now, switch back to the branch where the changes were mistakenly committed, such as Introduction_summary in my case:
-git switch Introduction_summary 
If the changes were not pushed to the remote repository, you can remove the commit locally with:

-git reset --hard HEAD~1

If the changes were already pushed, you will need to force push to update the remote branch:

-git push --force

4. Push Changes to the Correct Branch:
Once the changes are moved to the intended branch, push them to the remote repository to ensure they are saved:
git push origin main

This process ensures that the changes are placed in the right branch while keeping the project history clean and avoiding unnecessary merge conflicts. Mistakes like these are part of the learning curve when using Git, and resolving them efficiently is a valuable skill! Let me know if you need help implementing these steps. This will be helpful for future projects.

**Comment by jessiezhang24** [comment]
Hi Gunisha,

Thank you for sharing and outlining the detailed steps!

One additional suggestion is that before using `git push --force`, it might be helpful to double-check with the team to ensure no one else is working on the same branch. Force pushing can overwrite others’ changes if they have also pushed to the same branch.

Best,
Jessie
