### ISSUE TITLE
Add \newpage Markers to Rmd for New Page Before Each Section

### ISSUE THREAD

**Issue by gunishakaur** [gunishakaur/Dynamic33#12]
Hi,

It would be helpful to add \newpage markers to the Rmd file so that a new page is forced before each section. This would improve the document formatting and ensure that each section starts on a new page when rendered.

Could you please add \newpage before each section header in the Rmd file to implement this?

Thank you!

Best regards,
Gunisha Kaur

**Comment by derekrodgers** [comment]
Created PR for this #13
