### ISSUE TITLE
Issues with Pushing Changes to GitHub Repository: HTTPS Login Failed and Permission Denied

### ISSUE THREAD

**Issue by jessiezhang24** [gunishakaur/Dynamic33#9]
Dear team,

I cloned the repository locally but encountered several issues while attempting to push changes to the remote repository via the terminal. The specific errors include:
  1) HTTPS login Issues: The repository was initially configured for HTTPS instead of SSH, and I had trouble authorizing remote access using my GitHub login username and password. (*Solved*)
  2) Permission Denied: After resolving the SSH key issue, I encountered a “Permission denied” error due to a lack of certain access to the repository.

#### The error message are shown below:
**HTTPS login Issues**: 
change to ssh key: remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/gunishakaur/Dynamic33.git/'

Solution:   
Resolved by updating the remote URL to use SSH via the terminal command:  `git remote set-url origin git@github.com:gunishakaur/Dynamic33.git`

**Permission Denied**:
ERROR: Permission to gunishakaur/Dynamic33.git denied to jessiezhang24.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights and the repository exists.

**Does anyone know how to handle this “Permission denied” error? I suspect it might be related to my access permissions to this repository.** Any help or guidance would be appreciated!

With kind regards,
Jessie

**Comment by gunishakaur** [comment]
Hi Jessie,

It looks like you’ve already made great progress by resolving the HTTPS login issue and switching to SSH authentication. As for the "Permission denied" error, you're correct that it typically points to access permissions, especially when the error mentions the specific user jessiezhang24 not having permission.

Here are a few things you can check to resolve this:

1. Ensure Correct Access Rights: Double-check that you (as the owner) have granted the proper permissions to jessiezhang24. You can verify this by going to your GitHub repository, navigating to the "Settings" tab, and then selecting "Collaborators & teams" under the "Access" section. Ensure that the user jessiezhang24 has the necessary permissions (write access, at least).

2. Check SSH Key Setup: It’s also important to verify that the SSH key being used for authentication is correctly set up on the GitHub account. You can do this by checking if the correct SSH key is listed in your GitHub SSH settings (under "Settings" -> "SSH and GPG keys").

3. Repository Existence: Confirm that the repository Dynamic33 exists under your GitHub account and that the collaborator has access to it.

Additionally, I’ve already provided permission to all collaborators and set the ruleset with restrictions on deletions and blocking force pushes. This ensures that we maintain control over changes and prevent any unintended modifications.

If everything is in place and the issue persists, it may be worth asking the collaborator to re-add their SSH key to their GitHub account and try again.

Let me know if you need any further assistance!

Best regards,
Gunisha
